import type { Metadata } from "next";
import { Inter, Roboto_Mono, Pacifico } from "next/font/google";
import "./globals.css";

// 1. Pacifico (your original cursive font - unchanged)
const pacifico = Pacifico({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-pacifico', // Keeps your original CSS variable
});

// 2. Inter as Geist Sans replacement (similar modern sans-serif)
const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-geist-sans', // Preserves your variable name
  display: 'swap',
});

// 3. Roboto Mono as Geist Mono replacement (clean monospace)
const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono', // Keeps your original variable
  display: 'swap',
});

// Your original metadata - unchanged
export const metadata: Metadata = {
  title: "Readdy Site",
  description: "Generated by Readdy",
};

// Layout structure remains identical
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`
        ${inter.variable} 
        ${robotoMono.variable} 
        ${pacifico.variable} 
        antialiased
      `}>
        {children}
      </body>
    </html>
  );
}